### ISSUE TITLE
How can I get the draw instance so I can use things like the .deleteAllI() method?

### ISSUE THREAD

**Issue by chriswhong** [kturney/ember-mapbox-gl-draw#5]
Hi, thanks for a great ember add-on.  I started implementing it in an app this morning, and hit this snag:

I am using mapbox-gl-draw to select from an existing geojson layer of polygons.  When the user starts using the polygon tool, draw draws the polygon as expected.  When they close the polygon, I want to trigger some action with the resulting geometry, and I want to delete the drawn polygon using draw's `deleteAll()` method.  To do this, I need access to the `draw` instance, and I'm not clear on how to get ahold of that from the controller that's handling the map events.

Any advice?  Thanks!

**Comment by allthesignals** [comment]
@chriswhong I think I was able to achieve this by adding it explicitly: https://github.com/NYCPlanning/labs-zola/blob/develop/app/components/main-map.js#L36. 

Then I can reference here:https://github.com/NYCPlanning/labs-zola/blob/develop/app/components/main-map.js#L212.

**Comment by kturney** [comment]
@allthesignals solution seems reasonable to me.

If you want to get fancy with [ember-composable-helpers](https://github.com/DockYard/ember-composable-helpers) you could possibly rig up something like
```handlebars
{{map.control (compute
  (action 'actionLookingForDrawControlAndThatReturnsTheDrawControl')
  (draw-control touchEnabled=true)
) 'top-left'}}
```

You'd probably also want something that clears the draw control after the hbs gets cleared.

**Comment by chriswhong** [comment]
Got it working in the controller the way @allthesignals described.

**Comment by kturney** [comment]
👍
